version: '3.8'

services:
  db1:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - db2:/var/lib/postgresql/data

  db2:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5434:5432'
    volumes:
      - db2:/var/lib/postgresql/data

volumes:
  db1:
    driver: local
  db2:
    driver: local