name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run Tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2.5.0
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'